#Author: Menesay
#01/08/2022
#Rock Scissors Paper game

import random
import time

def game():
    print("-------------------------------------")
    print("      Rock Scissors Paper Game       ")
    print("             Menesay                 ")
    print("-------------------------------------")

    list = ['rock','scissors','paper' ]

    computer = random.choice(list)
    time.sleep(1)
    user = input("rock (1), scissors (2), paper (3): ")

       
    while user != '1' or user != '2' or user != '3':

        if user == '1' or user == '2' or user == '3':
            break

        user = input("rock (1), scissors (2), paper (3): ")
        print("Please enter a valid string or integer")

        


    #resut=0 draws
    #result=1 win
    #result=2 lose

    result = 1



    if computer == 'rock':

        if user == 'rock' or user == '1':
            result = 0

        elif user == 'scissors' or user == '2':
            result = 2 

        elif user == 'paper' or user == '3':
            result = 1

    elif computer == 'scissors':

        if user == 'rock' or user == '1':
            result = 1

        elif user == 'scissors' or user == '2':
            result = 0

        elif user == 'paper' or user == '3':
            result = 2

    elif computer == 'paper':

        if user == 'rock' or user == '1':
            result = 2

        elif user == 'scissors' or user == '2':
            result = 1

        elif user == 'paper' or user == '3':
            result = 0



    if user == '1':
        user = 'rock'

    elif user == '2':
        user = 'scissors'

    elif user == '3':
        user = 'paper'


    time.sleep(0.5)
    print("")
    print("Computer is choicing...")
    print("")
    time.sleep(2)

    print("-----------------------------")
    print("Computers choice: "+computer)
    print("Your choice: "+user)
    print("-----------------------------")

    print("")

    time.sleep(0.5)

    if result == 0:

        print("----------")
        print("   Draw!  ")
        print("----------")

    elif result == 1:

        print("------------")
        print("  You win!  ")
        print("------------")

    elif result == 2:

        print("------------")
        print("  You lose! ")
        print("------------")

def play_again():

    time.sleep(0.5)
    print("")
    response = input("Do you want to play again? (yes or no)")
    response = response.upper()

    if response == 'YES':
        return True

    elif response == 'NO':
        return False

    while response != 'YES' or response != 'NO':

        response = input("Do you want to play again? (yes or no)")
        response = response.upper()

        if response == 'YES' or response == 'NO':

            break


game()

while play_again():
    game()

##############################################
#                                            #
#              DUVİLER                       #
#                DUVİDİR...                  #
#                                            #
##############################################
   # MMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMMMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
#    WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
  #  WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWXXNNXNXXNNNNNWMMMMWWMMMMMWWMMMMWXXNXXNXXNNNXXNXNNNNNXNXXNXXXXXXNXXNNNXXXXXNXNNWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMM0;....','....oWMMMMWWWMMMWWWMMMM0;....','....''.....','...','....''....','...'dWMWWMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMk.           cNMMMMMWMMMMMWMMMMMk.                                            lWMMMMWWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMk.           cNMMMMWWWMMMWWWMMWMk.                   .                        lWMWMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO.     .     ':;;;;:c:;;;:::;;;;lxkkkkkkkkkkkkkkkkkkkkkkkkx;     ..     .     ':;;;;oXMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMk.                              ;XMMMMMWMMMMMWWMMMMMMWMMMMNc                        ,KMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMMk.                              ;XMMMMMWMMMMMWMMMMMMMWMMMMNc                        ,KMMMMMMMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
#    WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO.     .     ..    ..     ;oooookNMMMMWWWMMMMWWMMMMMXxlllll,     ..    .cooooooooooooollllloollllkNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMO.                        dMMMMMWWMMMMMWMMMMMWWMMMMM0'                 .OMMMMMWMMMMMO.           :NMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMk.                        dMMMMMWWMMMMMWMMMMMWMMMMMM0'                 .kMMMMMWMMMMMO.           :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWKxxxxxl.     .     ..    ..    .:xxxxxONMMMMWWWMMMMKxxxxxxo.     ..    .:::::lKMMMMMWWMMMMKo:::::c:::::lxxxxxkXWWMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWo      .     .     ..     .     .     ;XMMMMWWWMMMWd.      .     .     :XMMMMMWWMMMMWWMMMMWWMMMMMWMMMMMk.    .OMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWl                                     ;XMMMMMWMMMMMd                   :XMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
  #  WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMN00000000000Oo,'''',,''''',,''''..     .     ..    ,k00000000000l.     .'''''',,''''oNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMWO;'''';x00000XWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMk...  ..... .oNNNNNNNNNNNNNNNNNNd.     .     ..    ...   ...   ...     ,0NNNNNNNNNNNNWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWNNNNN0;.....oWMWMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.           oMMMMMMWMMMMMWMMMMMx.                                     '0MMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMK,     oWMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWNXXXXXx............dWMMMMWWMMMMMWWMMMMx.......     .      .     .     .      ,0MMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMK:.....oXXXXXNWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMWMNo.....l0KKKKKKKKKKKXWMMMMWWMMMMWWWMMMMNKKKKKx'     ..    ..     .     ..     ,0MWMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWWMMMWX0KK00o'....cXMWMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMM0'                               '0MMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMWo     ,KMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMX:     :NMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM0,                               ,0MMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMWMMWWMMMMMWMMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMNc     cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMNOkkkkx:     ..     .     ;kkkkkkONWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWKkkkkkdc;;;;c0MMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMX:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMWl                  cWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMX:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMNl                  lWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
#    WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMXdlllllooooooOWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMXxlllllooooooooooooodooooooolllllxXMWWMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMO.    .xMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMM0'     dMMMMMWWMMMMMWMMMMMd      '0MMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMO.    .xMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM0'     dMMMMMMWMMMMMWMMMMMd      '0MMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .xMMMMWWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMKxxxxxdl::::coxxxxxxxxxxxkXMMMMWOc:::::ldxxxxxKWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .kMWMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMO'    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMx.    '0MMMMWl           .kMMMMMWMMMMMM0'    .dMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMO'    .xMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    '0MMMMWl           .kMMMMMWMMMMMM0'     dMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMM
  #  WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMO'    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMx.    '0MMMMNl     ..    .kMMMMMWWMMMMM0,    .dMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMM0:'''';d00000KWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # MMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMWx.    '0MMMMNl     ..    .kMMMMMWWMMMMM0,    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWNNNNWXc.    cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    MMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWWMMMMO.    .xMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    '0MMMMWl           .kMMMMMWMMMMMM0'     dMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
 #   MMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMNXXXXXk,....'kMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMx.    '0MMMMWo...........'OMMMMMWWMMMMM0'    .xMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMNc     cNMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMM
  #  MMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWx'....:OKKKKKNWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMWx.    '0MWMMWXKKKKKKKKKKKKNWMMMMWWMMMWM0,    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMXc     cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # MMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMWo     ,KMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMd.    '0MMMMMWWMMMMWWMMMMMWMMMMMWMMMMMM0'     dMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
#    MMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMx.    '0WWWWWWMMMMMWWMMMMMWMMMMMWWWWWWW0'    .xMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   MMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWo.    ;KMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMWMMXkkkkkxc;;;;:OWMMMMWWMMMMWWWMMMWO:;;;;;cxkkkkkXWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMNc     cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  MMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMWo     ,KMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM0'     dMMMMMWWMMMMMWMMMMMd      '0MMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # MMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMWo     ,KMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM0'     dMMMMMMWMMMMMWMMMMWd      '0MMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    MMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWo.    ;KMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMXxoooooollllllllllllolllllodoooooxXWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMNc     cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   MMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMWl                  cWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMN:     :NMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  MMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMWo     ,KMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMNl                  cWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMWWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMWMWo.    ;KMWMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMNOxxxddoc::::cc::::ccc::::kWMWWWMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMWMNx:::::oxxxxdkXMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMWo     ;KMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM0'     dMMMMMMWMMMMMWMMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWMMMMMx.    .OMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMM0'     dMMMMMMWMMMMMWMMMMMWWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    'OMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMM
  #  WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWK0000Oo,''''lXMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMX0000Ox:'''',kWMMMMWWMMMMWWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMx.    'OMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMWMK;    .oNWWWWWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMWx.    ,OWWWWWWWMMMMWWMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMx.    '0MMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMK,     oWMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMd.    '0MMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMK,     oWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWNXXXXXd.....;0MMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMx.    'OMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMWMK;     oWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMWMNl.....l0KKKKKNMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMx.    '0MWMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMK,     oWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMX:     cWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMMWMMMMK,     oWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMX:     cNMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWWWWWWWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMx.    .OMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMWMK;     oWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMX:     cNMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMXo;;;;;xWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMx.    '0MWMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMK,     oWMMMMWWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMX:     cNMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMK;     lWMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMK,     oWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMX:     cWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMK;     lWMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
#    WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMWMK;     oWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMX:     cNMMMMWWWMMMWOlllllxNMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMKollllloooood0WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMx.    '0MWMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMK,     oWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMX:     cNMMMMMWMMMMNl     ;XMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMk.    .kMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMx.    .OMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMK,     oWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMX:     cNMMMMMWMMMMWl     ;XMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMk.    .kMMMMMWWMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMWMK;     oWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMX:     cNMMMMWWWMMMNl.    :XMMMMWWWMMMMWWMMMMMWWMMMMW0xdxddoc::::oKWWMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMx.    '0MWMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMK;     oWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMX:     cWMMMMWWMMMMNl     ;XMMMMWWWMMMMWWMMMMMWWMMMMNc     :XMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMx.    'OMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMK,     oWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMX:     cWMMMMMWMMMMWl     ;XMMMMMWMMMMMWWMMMMMMWMMMMNc     :XMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMx.    .OMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMM
  #  WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMK;     oWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMX:     cNMMMMWWWMMMNl     ,k000000000000000000000000Ol,''''oNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMWMWK00000d;''''c0WMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMWMK;     oWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMX:     cNMMMMWWWMMMNl     ..    ...    ..     ...   .dWWWWWWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMWMNc.    cXWWWWWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMK,     oWMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMX:     cWMMMMMWMMMMWl                                dMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMK:.....oXXXXXXWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMX:     cNMMMMWWMMMMNl     ...........................xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMNc     cNMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWXKKKKKo'....cXMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMX:     cNMWWMWWWMMMNl     ;OKKKKKKKKKKKKKKKKKKKKKKKKKNWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMWMNc     cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMX:     cNMMMMMWMMMMWl     ;XMMMMMWMMMMMWWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMX:     cNWWWWWWWWWWNl     ;XMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWo.    ;KMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMW0kkkkkd:;;;;;:;;;;;dOkkkk0NMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMNc     cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMWo     ,KMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMd.           dMMMMMWWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMWo     ,KMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMd.           dMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWo.    ;KMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMWKdooooddooood0WMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMNc     cNMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMN:     :NMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMWo     ,KMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWo.    ;KMWMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMWWWMMMMWWMMMMMWWMMMMWWWMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMXkdddddlc:c::xWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMWo.    ,KMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMO.    .xMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWx,''',ckOO0O0XWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .xMWMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWWWWWO'    .kMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMO'    .xMWMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMO.    .xMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMO.    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMO'    .xMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .xMWWMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .xMMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMO.    .xMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMO.    .xMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWWWWWO'    .xMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMWMO'    .xMWWMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWk;;;;;cxkkOkOXWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMO.    .xMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMWo     ,KMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMO.    .xMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMWo     ,KMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMXxoooodolcccckWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWo.    ;KMWMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMN:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo     ,KMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMWWMMMMX:     :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMWo     ,KMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMNxcccccodddddkXWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMNOdddddocccccdXWWMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMx.    .OMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMK,     oWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMK,     oWMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMO;,,,,:xOOOO0XWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMX0OOOOkc,,,,,xWMWMMWWWMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWWWWW0;    .dWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMk.    'OWWWWWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWMMMMMK,     oMMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMx.    .OMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMK:.....oXXXXXXXXXXXXNMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMNXXXXXXXXXXXXXXXXXXx'....;0MMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWXKKKKKo......'....,OMMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWx'.....'.....'.....c0KKKKXNWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMMMMMMWMMMMWl           .kMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMWo                  :NMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMWo.    ..    .xWWWWWWWWWWWWWWWWWWWMMMMMWWMMMMMWMMMMMWWMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWNo.    ..     .     :NMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWKOOOOOOOOOOOkl;,,,,;;,,,,;;;,,,;kWMMMMWWMMMMWWWMMMMWWMMMMMKl,,,,;:;,,,,;;,,,,;:;,,,;oOOOOOOOOOOOOOOOOOOKWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMWWMMMMX:                  dMMMMMMWMMMMMWMMMMMWMMMMMM0'                        lWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMX:                  dMMMMMMMMMMMMWMMMMMMMMMMMM0'                        lWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMNOddddddddddddddddddolccccllcccclllccccllccccclddddddddddddddddddddddddd0WWWMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMMMMMMWl                         '0MMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMNl                         '0MMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMWWWMMMMWWWMMMWkcccccclccccclcccccllcccccdXMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWMMMMMMWMMMMMMMMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMM
  #  WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
 #   WMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
#    WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
#    WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWWMMMM
  #  WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM
   # WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMMWWMMMMMWWMMMMWWMMMMMWMMMMMWWMMMM
 #   WMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
#    WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMMMMMMM
 #   WMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMM
  #  WMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMMWWMMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMMWWMMMMWWWMMMMWWMMMMWWWMMMWWWMMMMWWMMMMWWWMMMMWWMMMM
   # WMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMMWMMMMMWMMMMMWMMMMM

#HABULEN !